# Generated by Django 3.2 on 2021-04-20 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shelter', models.BooleanField(default=False)),
                ('shelter_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shelter_bio', models.TextField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=40)),
                ('disposition', models.CharField(max_length=30)),
                ('availability', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('picture_primary', models.ImageField(upload_to='')),
                ('picture_second', models.ImageField(blank=True, upload_to='')),
                ('picture_third', models.ImageField(blank=True, upload_to='')),
                ('gender', models.CharField(max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
